services:
  mongo:
    image: "hypertheory-web-mongo:1.0"
    container_name: "mongodb-web"
    build:
      context: .
      dockerfile: Dockerfile-Mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: TokyoJoe138!

  mongo-setup:
    image: "hypertheory-web-mongo:1.0"
    depends_on:
      - mongo
    entrypoint:
      [
        "bash",
        "-c",
        "sleep 20 && mongo --host mongodb://root:TokyoJoe138!@mongo:27017 config-data.js",
      ]
    restart: "no"

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8090:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=TokyoJoe138!
      - ME_CONFIG_MONGODB_SERVER=mongo

    restart: always
    depends_on:
      - mongo
