services:
  mongodb-sharded:
    image: "hypertheory-mongodb:1.0"
    container_name: "mongodb-sharded"
    build:
      context: .
      dockerfile: Dockerfile-Mongo
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-sharded
      - MONGODB_SHARDING_MODE=mongos
      - MONGODB_CFG_PRIMARY_HOST=mongodb-cfg
      - MONGODB_CFG_REPLICA_SET_NAME=cfgreplicaset
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ROOT_PASSWORD=TokyoJoe138!
    ports:
      - "27017:27017"
    restart: always

  mongodb-shard0:
    image: "hypertheory-mongodb:1.0"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard0
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongodb-sharded
      - MONGODB_ROOT_PASSWORD=TokyoJoe138!
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=shard0
    volumes:
      - "shard0_data:/bitnami"
    restart: always
    depends_on:
      - mongodb-sharded

  mongodb-cfg:
    image: "hypertheory-mongodb:1.0"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-cfg
      - MONGODB_SHARDING_MODE=configsvr
      - MONGODB_ROOT_PASSWORD=TokyoJoe138!
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=cfgreplicaset
    volumes:
      - "cfg_data:/bitnami"
    restart: always

  mongo-setup:
    image: "hypertheory-mongodb:1.0"
    container_name: mongo-setup
    depends_on:
      - mongodb-sharded
      - monggodb-shard0
      - mongodb-cfg
    entrypoint:
      [
        "bash",
        "-c",
        "sleep 20 && mongo --host mongodb://root:TokyoJoe138!@mongodb-sharded:27017 config-data.js",
      ]
    restart: "no"

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8090:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=TokyoJoe138!
      - ME_CONFIG_MONGODB_SERVER=mongodb-sharded
    restart: always
    depends_on:
      - mongodb-shard0
      - mongodb-cfg
      - mongodb-sharded

volumes:
  shard0_data:
    driver: local
  cfg_data:
    driver: local

networks:
  default:
    name: ht-network
